### ISSUE TITLE
[Documentation] - Highlight that you need python3-catkin-tools

### ISSUE THREAD

**Issue by chisarie** [ARoefer/rosvenv#3]
rosvenv uses `catkin build`, so I would highlight in the readme that for it to work you need to have previously installed

`sudo apt-get install python3-catkin-tools'

**Comment by ARoefer** [comment]
@vonHartz Can you investiagte?

**Comment by ARoefer** [comment]
Addressed in fa08298e5c9092779e3f019dca6b787a38d4b9cc
